apiVersion : apps/v1
kind: Deployment
metadata:
  name: "azurekubernetesservice-6eda"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "azurekubernetesservice-6eda"
  template:
    metadata:
      labels:
        app: "azurekubernetesservice-6eda"
    spec:
      containers:
        - name: "azurekubernetesservice-6eda"
          image: "seazureprd095mlacrwus.azurecr.io/azurekubernetesservice"
          ports:
          - containerPort: 8080